apiVersion: v1
kind: Service
metadata:
  name: autofix-devops-service
  labels:
    app: autofix-devops
spec:
  selector:
    app: autofix-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
